const toolsData = [
  {
    id: 1,
    title: "Chatsonic",
    description: "集成了多个 AI 模型的聊天工具，支持图像生成和语音识别。",
    icon: "https://v0.blob.com/pjtmy8OGJ.png",
    status: "已测试",
    statusColor: "green",
    statusIndicator: "green",
    views: "9",
    likes: "5",
    category: "AI 聊天",
    url: "https://chatsonic.com",
  },
  {
    id: 2,
    title: "Chai",
    description: "AI 聊天应用，能够根据用户输入的上下文进行智能对话。",
    icon: "https://v0.blob.com/pjtmy8OGJ.png",
    status: "已测试",
    statusColor: "green",
    statusIndicator: "green",
    views: "13",
    likes: "3",
    category: "AI 聊天",
    url: "https://chai.ml",
  },
  {
    id: 3,
    title: "Mitsuku",
    description: "多次获奖的 AI 聊天机器人，提供与人类进行自然对话的体验。",
    icon: "https://v0.blob.com/pjtmy8OGJ.png",
    status: "已测试",
    statusColor: "green",
    statusIndicator: "green",
    views: "5",
    likes: "1",
    category: "AI 聊天",
    url: "https://www.pandorabots.com/mitsuku/",
  },
  {
    id: 4,
    title: "Chatbot Studio",
    description: "AI 聊天机器人开发平台，适用于客服、销售等领域。",
    icon: "https://v0.blob.com/pjtmy8OGJ.png",
    status: "已测试",
    statusColor: "green",
    statusIndicator: "red",
    views: "14",
    likes: "1",
    category: "AI 聊天",
    url: "https://chatbotstudio.ai",
  },
  {
    id: 5,
    title: "BlenderBot",
    description: "Meta 开发的 AI 聊天机器人，具有丰富的对话能力。",
    icon: "https://v0.blob.com/pjtmy8OGJ.png",
    status: "已测试",
    statusColor: "green",
    statusIndicator: "red",
    views: "2",
    likes: "2",
    category: "AI 聊天",
    url: "https://blenderbot.ai",
  },
  {
    id: 6,
    title: "DialoGPT",
    description: "微软开发的对话生成模型，优化了人类对话的自然性。",
    icon: "https://v0.blob.com/pjtmy8OGJ.png",
    status: "已测试",
    statusColor: "green",
    statusIndicator: "red",
    views: "6",
    likes: "1",
    category: "AI 聊天",
    url: "https://huggingface.co/microsoft/DialoGPT-large",
  },
  {
    id: 7,
    title: "Jasper",
    description: "专注于创意写作的 AI，能够生成文章、博客和广告文案。",
    icon: "https://v0.blob.com/pjtmy8OGJ.png",
    status: "已测试",
    statusColor: "green",
    statusIndicator: "green",
    views: "3",
    likes: "1",
    category: "AI 聊天",
    url: "https://jasper.ai",
  },
  {
    id: 8,
    title: "Chatbot.com",
    description: "帮助企业创建 AI 聊天机器人，提供自动化客户服务。",
    icon: "https://v0.blob.com/pjtmy8OGJ.png",
    status: "已测试",
    statusColor: "green",
    statusIndicator: "green",
    views: "1",
    likes: "1",
    category: "AI 聊天",
    url: "https://chatbot.com",
  },
]
